import { createSlice } from "@reduxjs/toolkit";
//
 import image1 from "../assets/images/images/Asus-Products/Asus-Tuf-Gaming.jpg"
 import image2 from "../assets/images/images/Asus-Products/Asus-Rog-mouse.jfif"
 import image3 from "../assets/images/images/Asus-Products/Asus-Monitor-VP249QGR.jfif"
 import image4  from "../assets/images/Products-images/Laptops/Laptop4/91P7uBC9DML._AC_SX679_.jpg"
 import image5 from "../assets/images/Products-images/Laptops/Laptop6/714wwp3NVvL._AC_SX425_.jpg"
 import image6 from "../assets/images/Products-images/Laptops/Laptop7/71+24XBsCEL._AC_SX679_.jpg"
 import image7  from "../assets/images/Products-images/Laptops/Laptop8/81tAI6HxHDL._AC_SX679_.jpg"
 import image8 from "../assets/images/Products-images/Laptops/Laptop9/71gNkSISiYL._AC_SX679_.jpg"
 import image9 from "../assets/images/Products-images/Laptops/Laptop10/71qiYEsQmHL._AC_SX425_.jpg"
 import image10 from "../assets/images/Products-images/Laptops/Laptop11/81fstJkUlaL._AC_SX425_.jpg"
 import image11 from "../assets/images/Products-images/Laptops/Laptop12/71CR6drcruL._AC_SX425_.jpg"
 import image12 from "../assets/images/Products-images/Laptops/Laptop13/71SkS+1kA0L._AC_SX679_.jpg"
 import image13 from "../assets/images/Products-images/Laptops/Laptop14/71vxTjD6CQS._AC_SX679_.jpg"
 import image14 from "../assets/images/Products-images/Laptops/Laptop15/71lt6nqkEmL._AC_SX679_.jpg"
 import image15 from "../assets/images/images/Headphones/asus-rog-delta-s-gaming-headset-mobile-v4.jpg"
 import image16 from "../assets/images/images/Headphones/New-Original-ASUS-ROG-Cetra-True-Wireless-Gaming-Headphone-ANC-Noise-Canceling-Bluetooth-Earphone-For-ROG.jpg_640x640.jpg"
 import image17 from "../assets/images/images/Headphones/asus-rog-cetra-core.jpg"
 import image18 from "../assets/images/images/Headphones/asus_strix_pro_box_ndtv.jpg"
 import image19 from "../assets/images/images/Mouses/asus_rog_spatha_x_black_wirele_1664334635_c9ef0631.jpg"
 import image20 from "../assets/images/images/Mouses/Rog Strix impact Wireless.jpg"
 import image21 from "../assets/images/images/Mouses/rog-chakram-x-review-banner.jpg"
 import image22 from "../assets/images/images/Mouses/rog strix impact.webp"
 import image23 from "../assets/images/images/Screens/ROG Swift OLED PG42UQ, PG48UQ_R1.jpg"
 import image24 from "../assets/images/images/Screens/Rog Strix XG258Q.jpg"
 import image25 from "../assets/images/images/Screens/Asus PA34VC curver.webp"
 import image26 from "../assets/images/images/Screens/asus-proart-PA348CGV-5.webp"
 import image27 from "../assets/images/images/Backpack/HB-01 Gaming Backpack.jpg"
 import image28 from "../assets/images/images/Backpack/Rog Ranger Bp2701 Bag.jpg"
 import image29 from "../assets/images/images/Backpack/Rog Ranger BP3703.jpg"
 import image30 from "../assets/images/images/Backpack/Tuf Gaming BP2700T.jpg"





//
const definition =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel dapibus leo. Curabitur libero dui, tincidunt sit amet ultricies et, rhoncus ut dolor. Sed at elit finibus, pulvinar enim ut, ullamcorper odio. Morbi nec iaculis lectus. Etiam cursus mauris quis nunc condimentum, vel tincidunt magna placerat. Aliquam erat volutpat. Maecenas gravida turpis lorem, et tincidunt erat convallis sit amet. Duis volutpat quis sapien at tempus. In tincidunt ante ut nisi posuere.";
const colors = { first: "red", second: "blue", third: "brown" };
const sizes = {
  first: "S",
  second: "M",
  third: "L",
  fourth: "XL",
  fifth: "XXL",
};
const description =
  "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu dis parturient montes, nascetur ridiculus mus. Donec quam felis, dis parturient montes, nascetur ridiculus mus. Donec quam felis,.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu dis parturient montes, nascetur ridiculus mus. Donec quam felis, dis parturient montes, nascetur ridiculus mus. Donec quam felis,.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu dis parturient montes, nascetur ridiculus mus. Donec quam felis, dis parturient montes, nascetur ridiculus mus. Donec quam felis,.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.";
const availability = "";
const shortdescription = "";
const features = {
  one: "consectetuer adipiscing elit",
  two: "Aenean massa. Cum sociis natoque penatibus",
  three: "nascetur ridiculus mus. Donec quam felis",
  four: "ultricies nec, pellentesque eu.",
};
const shortDes = "17/4/2023"

const popularProducts = [
  {
    id: "1p",
    name: "Tuf-Gaming",
    amount: 1,
    // image: "./images/Asus-Products/Asus-Tuf-Gaming.jpg",
    image: image1,
    price: { currentPrice: "300", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },

  {
    id: "2p",
    name: "Rog-mouse",
    amount: 1,
    // image: "./images/Asus-Products/Asus-Rog-mouse.jfif",
    image: image2,
    price: { currentPrice: "420", oldPrice: "480" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },

  {
    id: "3p",
    name: "Asus-Monitor",
    amount: 1,
    // image: "./images/Asus-Products/Asus-Monitor-VP249QGR.jfif",
    image: image3,
    price: { currentPrice: "600", oldPrice: "750" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Sceen",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },

  {
    id: "4p",
    name: "ASUS TUF F17",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop4/91P7uBC9DML._AC_SX679_.jpg",
    image: image4,
    price: { currentPrice: "800", oldPrice: "950" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "5p",
    name: "TUF F17.3",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop6/714wwp3NVvL._AC_SX425_.jpg",
    image: image5,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "6p",
    name: "VivoBook S14",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop7/71+24XBsCEL._AC_SX679_.jpg",
    image: image6,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "7p",
    name: "VivoBook Pro 15",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop8/81tAI6HxHDL._AC_SX679_.jpg",
    image: image7,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "8p",
    name: "VivoBook S15 S533",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop9/71gNkSISiYL._AC_SX679_.jpg",
    image: image8,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "9p",
    name: "VivoBook 15.6 FHD",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop10/71qiYEsQmHL._AC_SX425_.jpg",
    image: image9,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "10p",
    name: "VivoBook15 Light",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop11/81fstJkUlaL._AC_SX425_.jpg",
    image: image10,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "11p",
    name: "VivoBook 14",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop12/71CR6drcruL._AC_SX425_.jpg",
    image: image11,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "12p",
    name: "VivoBook S533",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop13/71SkS+1kA0L._AC_SX679_.jpg",
    image: image12,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "13p",
    name: "VivoBook S15 S5",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop14/71vxTjD6CQS._AC_SX679_.jpg",
    image: image13,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "14p",
    name: "VivoBook Go 14 Flip",
    amount: 1,
    // image: "./Products-images/Laptops/Laptop15/71lt6nqkEmL._AC_SX679_.jpg",
    image: image14,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "15p",
    name: "Asus Rog Delta",
    amount: 1,
    // image: "./images/Headphones/asus-rog-delta-s-gaming-headset-mobile-v4.jpg",
    image: image15,
    price: { currentPrice: "800", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Keyboard",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "16p",
    name: "Asus ROG-Cetra ",
    amount: 1,
    // image: "./images/Headphones/New-Original-ASUS-ROG-Cetra-True-Wireless-Gaming-Headphone-ANC-Noise-Canceling-Bluetooth-Earphone-For-ROG.jpg_640x640.jpg",
    image: image16,
    price: { currentPrice: "600", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Keyboard",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "17p",
    name: "Asus Rog Core",
    amount: 1,
    // image: "./images/Headphones/asus-rog-cetra-core.jpg",
    image: image17,
    price: { currentPrice: "500", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Keyboard",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "18p",
    name: "Asus Strix Pro",
    amount: 1,
    // image: "./images/Headphones/asus_strix_pro_box_ndtv.jpg",
    image: image18,
    price: { currentPrice: "500", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },

  //Mouses
  {
    id: "19p",
    name: "Asus Rog Spatha",
    amount: 1,
    // image: "./images/Mouses/asus_rog_spatha_x_black_wirele_1664334635_c9ef0631.jpg",
    image: image19,
    price: { currentPrice: "500", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Mouse",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "20p",
    name: "Rog Strix impact ",
    amount: 1,
    // image: "./images/Mouses/Rog Strix impact Wireless.jpg",
    image: image20,
    price: { currentPrice: "680", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Mouse",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "21p",
    name: "Rog Chakram X ",
    amount: 1,
    // image: "./images/Mouses/rog-chakram-x-review-banner.jpg",
    image: image21,
    price: { currentPrice: "750", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Mouse",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "22p",
    name: "Rog Strix impact",
    amount: 1,
    // image: "./images/Mouses/rog strix impact.webp",
    image: image22,
    price: { currentPrice: "550", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Mouse",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  //Screens
  {
    id: "23p",
    name: "ROG Swift PG42UQ",
    amount: 1,
    // image: "./images/Screens/ROG Swift OLED PG42UQ, PG48UQ_R1.jpg",
    image: image23,
    price: { currentPrice: "1200", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Screen",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "24p",
    name: "Rog Strix XG258Q",
    amount: 1,
    // image: "./images/Screens/Rog Strix XG258Q.jpg",
    image: image24,
    price: { currentPrice: "900", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Screen",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "25p",
    name: "Asus PA34VC curver",
    amount: 1,
    // image: "./images/Screens/Asus PA34VC curver.webp",
    image: image25,
    price: { currentPrice: "1000", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Screen",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "26p",
    name: "Proart PA348CGV-5",
    amount: 1,
    // image: "./images/Screens/asus-proart-PA348CGV-5.webp",
    image: image26,
    price: { currentPrice: "750", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Screen",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },

  //Backpack

  {
    id: "27p",
    name: "HB-01 Gaming ",
    amount: 1,
    // image: "./images/Backpack/HB-01 Gaming Backpack.jpg",
    image: image27,
    price: { currentPrice: "550", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Backpack",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "28p",
    name: "Rog Ranger Bp2701 ",
    amount: 1,
    // image: "./images/Backpack/Rog Ranger Bp2701 Bag.jpg",
    image: image28,
    price: { currentPrice: "650", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Backpack",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "29p",
    name: "Rog Ranger BP3703 ",
    amount: 1,
    // image: "./images/Backpack/Rog Ranger BP3703.jpg",
    image: image29,
    price: { currentPrice: "800", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Backpack",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "30p",
    name: "Tuf Gaming BP2700T ",
    amount: 1,
    // image: "./images/Backpack/Tuf Gaming BP2700T.jpg",
    image: image30,
    price: { currentPrice: "450", oldPrice: "1300" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Backpack",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
];
const productsSlice = createSlice({
  name: "ui",
  initialState: { id: 1, productComponent: false, products: popularProducts },
  reducers: {
    toggle(state) {
      state.cartIsVisible = !state.cartIsVisible;
    },
    setId(state, action) {
      state.id = action.payload;
    },
    showProduct(state, action) {
      state.productComponent = action.payload;
    },
  },
});

export const productsActions = productsSlice.actions;

export default productsSlice;
