import { createSlice } from "@reduxjs/toolkit"; 
// image: "./images/Recommended Laptops/51ixmFrp6NL._AC_UF1000,1000_QL80_.jpg",
// "./images/Recommended Laptops/Asus_ROG_Strix_G15_gaming_laptop_AMD.jpg",
// image: "./images/Recommended Laptops/Asus-ProArt.jpg",

import image1 from "../assets/images/images/Recommended Laptops/51ixmFrp6NL._AC_UF1000,1000_QL80_.jpg"
import image2 from "../assets/images/images/Recommended Laptops/Asus_ROG_Strix_G15_gaming_laptop_AMD.jpg"
import image3 from "../assets/images/images/Recommended Laptops/Asus-ProArt.jpg"
import image4 from "../assets/images/images/Recommended Laptops/Asus-Zenbook-Pro-Duo-lid-profile.jpg"
import image5 from "../assets/images/images/Recommended Laptops/displays-960x505.jpg"
import image6 from "../assets/images/images/Recommended Laptops/vsDbdkzohMEQRNUXjgtBPG.jpg"
import image7 from "../assets/images/images/Recommended Laptops/2018-ASUS-Laptop-Line-Up.webp"
import image8 from "../assets/images/images/Recommended Laptops/Asus_ROG_Strix_G15_gaming_laptop_AMD.jpg"
import image9 from "../assets/images/images/Recommended Laptops/asus_ux9702aa_xb79ft_17_3_zenbook_17_fold_1723069.jpg"
import image10 from "../assets/images/images/Recommended Laptops/Asus-Duo-16-1024x567.webp"
import image11 from "../assets/images/images/Asus-details-products/ROG-2022.jpg"
import image12 from "../assets/images/images/Asus-details-products/Asus-Monitor-VG278QR.jpg"
import image13 from "../assets/images/images/Asus-details-products/Asus-ROG-Wired-Mouse.png"


const definition =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vel dapibus leo. Curabitur libero dui, tincidunt sit amet ultricies et, rhoncus ut dolor. Sed at elit finibus, pulvinar enim ut, ullamcorper odio. Morbi nec iaculis lectus. Etiam cursus mauris quis nunc condimentum, vel tincidunt magna placerat. Aliquam erat volutpat. Maecenas gravida turpis lorem, et tincidunt erat convallis sit amet. Duis volutpat quis sapien at tempus. In tincidunt ante ut nisi posuere.";

const colors = { first: "red", second: "blue", third: "brown" };
const sizes = {
  first: "S",
  second: "M",
  third: "L",
  fourth: "XL",
  fifth: "XXL",
};
const description =
  "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu dis parturient montes, nascetur ridiculus mus. Donec quam felis, dis parturient montes, nascetur ridiculus mus. Donec quam felis,.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu dis parturient montes, nascetur ridiculus mus. Donec quam felis, dis parturient montes, nascetur ridiculus mus. Donec quam felis,.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu dis parturient montes, nascetur ridiculus mus. Donec quam felis, dis parturient montes, nascetur ridiculus mus. Donec quam felis,.Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.";
const availability = "";
const features = {
  one: "consectetuer adipiscing elit",
  two: "Aenean massa. Cum sociis natoque penatibus",
  three: "nascetur ridiculus mus. Donec quam felis",
  four: "ultricies nec, pellentesque eu.",
};
const shortDes = "17/4/2023"

const recommendedProducts = [
  {
    id: "1",
    name: "Tuf-Gamingrec",
    amount: 1,
    // image: "./images/Recommended Laptops/51ixmFrp6NL._AC_UF1000,1000_QL80_.jpg",
    image: image1,
    price: { currentPrice: "700", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "850",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "2",
    name: "ROG Strix G15",
    amount: 1,
    // image:"./images/Recommended Laptops/Asus_ROG_Strix_G15_gaming_laptop_AMD.jpg",
    image: image2,
    price: { currentPrice: "1200", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "1000",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "3",
    name: "Asus-ProArt",
    amount: 1,
    // image: "./images/Recommended Laptops/Asus-ProArt.jpg",
    image: image3,
    price: { currentPrice: "600", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "4",
    name: "Zenbook Pro Duo",
    amount: 1,
    // image: "./images/Recommended Laptops/Asus-Zenbook-Pro-Duo-lid-profile.jpg",
    image: image4,
    price: { currentPrice: "580", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "5",
    name: "Asus demo 5",
    amount: 1,
    // image: "./images/Recommended Laptops/displays-960x505.jpg",
    image: image5,
    price: { currentPrice: "690", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "6",
    name: "Asus demo 6",
    amount: 1,
    image: image6,
    // image: "./images/Recommended Laptops/vsDbdkzohMEQRNUXjgtBPG.jpg",
    price: { currentPrice: "799", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "7",
    name: "ASUS Line-Up 2018",
    amount: 1,
    image: image7,
    // image: "./images/Recommended Laptops/2018-ASUS-Laptop-Line-Up.webp",
    price: { currentPrice: "900", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "8",
    name: "ROG Strix",
    amount: 1,
    image: image8,
    // image:"./images/Recommended Laptops/Asus_ROG_Strix_G15_gaming_laptop_AMD.jpg",
    price: { currentPrice: "660", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  // {
  //   id: "9",
  //   name: "Asus demo 9",
  //   amount: 1,
  //   image: "./images/Recommended Laptops/51ixmFrp6NL._AC_UF1000,1000_QL80_.jpg",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Laptop",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },
  {
    id: "9",
    name: "Asus_ux9702",
    amount: 1,
    image: image9,
    // image:"./images/Recommended Laptops/asus_ux9702aa_xb79ft_17_3_zenbook_17_fold_1723069.jpg",
    price: { currentPrice: "300", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "10",
    name: "Asus Duo 16",
    amount: 1,
    image: image10,
    // image: "./images/Recommended Laptops/Asus-Duo-16-1024x567.webp",
    price: { currentPrice: "300", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  // {
  //   id: "12",
  //   name: "Tuf-Gamingrec",
  //   amount: 1,
  //   image: "./images/zenBook-pro-duo.jfif",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Laptop",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },
  // {
  //   id: "13",
  //   name: "Tuf-Gamingrec",
  //   amount: 1,
  //   image: "./images/Vivibook-m409B.jfif",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Laptop",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },
  // {
  //   id: "14",
  //   name: "Tuf-Gamingrec",
  //   amount: 1,
  //   image: "./images/Asus-Ryzen.jfif",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Laptop",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },
  // {
  //   id: "15",
  //   name: "Tuf-Gamingrec",
  //   amount: 1,
  //   image: "./images/VivioBook14.jpg",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Laptop",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },
  // {
  //   id: "16",
  //   name: "Tuf-Gamingrec",
  //   amount: 1,
  //   image: "./images/Asus-VivoBook-x556UQ.jpg",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Laptop",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },
  // {
  //   id: "17",
  //   name: "Tuf-Gamingrec",
  //   amount: 1,
  //   image: "./images/zenBook-pro-duo.jfif",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Laptop",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },
  // {
  //   id: "18",
  //   name: "Tuf-Gamingrec",
  //   amount: 1,
  //   image: "./images/zenBook-pro-duo.jfif",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Laptop",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },

  // {
  //   id: "212",
  //   name: "this is Keyboard",
  //   amount: 1,
  //   image: "./images/zenBook-pro-duo.jfif",
  //   price: { currentPrice: "300", oldPrice: "350" },
  //   definition: definition,
  //   colors: colors,
  //   sizes: sizes,
  //   catagory: "Keyboard",
  //   availability: "250",
  //   description: description,
  //   shortdescription: shortDes,
  //   features: features,
  // },

  //More Products
  {
    id: "23",
    // image: "./images/Asus-details-products/ROG-2022.jpg",
    image: image11,
    name: "Asus Super Laptop",
    tags: { tag1: "Powerful", tag2: "high quality", tag3: "Wonderful design " },
    // price: "150",
    amount: 1,
    price: { currentPrice: "300", oldPrice: "350" },
    // price: { currentPrice: 300, oldPrice: function(){return this.price.currentPrice + 1}},
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "24",
    // image: "./images/Asus-details-products/Asus-Monitor-VG278QR.jpg",
    image: image12,
    name: "Asus high display",
    tags: { tag1: "Wonderful design", tag2: "high quality", tag3: "Powerful" },
    // price: "150",
    amount: 1,
    price: { currentPrice: "300", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
  {
    id: "25",
    // image: "./images/Asus-details-products/Asus-ROG-Wired-Mouse.png",
    image: image13,
    name: "Asus Rog mouse",
    tags: { tag1: "Powerful", tag2: "Wonderful design", tag3: "high quality" },
    // price: "150",
    amount: 1,
    price: { currentPrice: "300", oldPrice: "350" },
    definition: definition,
    colors: colors,
    sizes: sizes,
    catagory: "Laptop",
    availability: "250",
    description: description,
    shortdescription: shortDes,
    features: features,
  },
];

const recommendedProductsSlice = createSlice({
  name: "recommended",
  initialState: {
    id: 1,
    productComponent: false,
    products: recommendedProducts,
  },
  reducers: {
    setId(state, action) {
      state.id = action.payload;
    },
    showProduct(state, action) {
      state.productComponent = action.payload;
    },
  },
});

export const recommendedProductsActions = recommendedProductsSlice.actions;

export default recommendedProductsSlice;
